# Generated by Django 2.1.7 on 2019-04-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.IntegerField()),
                ('billDate', models.CharField(max_length=100)),
                ('shopId', models.IntegerField()),
                ('itemName', models.CharField(max_length=1000)),
                ('itemRate', models.CharField(max_length=100)),
                ('itemHsnCode', models.CharField(max_length=20)),
                ('itemQuantity', models.IntegerField()),
                ('itemMrp', models.CharField(max_length=100)),
                ('itemGst', models.CharField(max_length=10)),
                ('itemScheme', models.CharField(max_length=10)),
                ('itemTotal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.IntegerField()),
                ('shopId', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
