# Generated by Django 2.1.7 on 2019-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ownerName', models.CharField(max_length=200)),
                ('gstNo', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('areaCode', models.IntegerField()),
                ('address', models.CharField(max_length=2500)),
                ('phoneNo', models.CharField(max_length=10)),
            ],
        ),
    ]
