# Generated by Django 2.1.7 on 2019-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('hsnCode', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('mrp', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=10)),
            ],
        ),
    ]
