# Generated by Django 2.1.7 on 2019-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='stockCode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
